# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Merge Release Into Main

on:
  push:
    branches:
      - 'release/*'

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  RELEASE_BRANCH: ${{ github.ref_name }}

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: env vars
        run: |
          echo "Default: $DEFAULT_BRANCH"
          echo "Release: $RELEASE_BRANCH"

      - name: perform merge
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git pull
          git checkout "$DEFAULT_BRANCH"
          git pull
          git status
          git branch -a
          git checkout -b automated/merge-release-to-main
          git merge "$RELEASE_BRANCH" --allow-unrelated-histories --no-edit
          git push origin -u automated/merge-release-to-main
          git status
        continue-on-error: true

      # https://github.com/marketplace/actions/create-pull-request
      - name: create pull request
        id: open-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          base: ${{ github.event.repository.default_branch }}
          branch: automated/merge-release-to-main
          commit-message: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          body: |
            :robot: _Automated Pull Request_ :robot:

            Merging **${{ github.ref_name }}** into **${{ github.event.repository.default_branch }}**.

            :warning: _If there are conflicts, you can resolve them directly on this branch._
          delete-branch: true
          draft: false

      # https://github.com/marketplace/actions/enable-pull-request-automerge
      - name: enable automerge
        if: steps.open-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pull-request-number }}
          merge-method: merge
