# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Merge Release Into Main

on:
  push:
    branches:
      - 'release/*'

jobs:
  main:
    name: Create PR Release to Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      # https://github.com/marketplace/actions/github-action-for-creating-pull-requests
      - name: create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          target_branch: ${{ github.event.repository.default_branch }}
          title: "[Automated] ${{ github.event.pull_request.head.ref }} into ${{ github.event.repository.default_branch }}"
          body: ":robot: *Automated Pull Request.* :robot: Merging ${{ github.event.pull_request.head.ref }} into ${{ github.event.repository.default_branch }}."
          reviewer: jessesquires
          assignee: jessesquires
