# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Rebase Pull Request

on:
  pull_request:
    types: [labeled]

env:
  BASE_BRANCH: ${{ github.base_ref }}

jobs:
  main:
    if: ${{ github.event.label.name == 'rebase' }}
    name: Rebase
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: rebase on main
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git status
          git checkout main
          git pull
          git status
          git checkout "$BASE_BRANCH"
          git status
          git rebase main
          git status
          git push -f
          git status

      # https://github.com/marketplace/actions/actions-ecosystem-remove-labels
      - name: remove rebase label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: rebase
