# GitHub Actions Virtual Environments
# https://github.com/actions/virtual-environments/

name: Start New Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        type: choice
        description: Version Bump
        options:
        - major
        - minor
        - patch
        default: 'minor'
        required: true

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    name: New Release
    runs-on: macos-11
    steps:
      - name: git checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: ruby versions
        run: |
          ruby --version
          gem --version

      # https://github.com/ruby/setup-ruby
      - name: ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: major version bump
        if: ${{ github.event.inputs.version_bump == 'major' }}
        run: |
          echo "${{ github.event.inputs.version_bump }}"

      - name: minor version bump
        if: ${{ github.event.inputs.version_bump == 'minor' }}
        run: |
          echo "${{ github.event.inputs.version_bump }}"

      - name: patch version bump
        if: ${{ github.event.inputs.version_bump == 'patch' }}
        run: |
          echo "${{ github.event.inputs.version_bump }}"

      - name: write env
        run: |
          echo "app_version=$(./script.rb)" >> $GITHUB_ENV
          echo "release_branch=release/$(./script.rb)" >> $GITHUB_ENV

      - name: read env
        run: |
          echo "Version: ${{ env.app_version }}"
          echo "Branch: ${{ env.release_branch }}"
          echo "${{ env.app_version }}" >> VERSION.txt

      - name: set git config
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: create release branch
        run: |
          git status
          git checkout "$DEFAULT_BRANCH"
          git pull
          git status
          git checkout -b "${{ env.release_branch }}"
          git push origin -u "${{ env.release_branch }}"
          git status

      - name: commit version bump
        run: |
          git status
          git checkout ${{ env.release_branch }}
          git add .
          git commit -m "[automated] version bump to ${{ env.app_version }}" || true
          git status
          git push
